const fs = require('fs');
const path = require('path');

const write = (filePath, content) => {
  const fullPath = path.join(__dirname, filePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content.trim() + '\n', 'utf8');
};

// ==========================================
// 1. STATIC CONTENT PAGES
// ==========================================
write('src/pages/StaticPages.tsx', `
import React from 'react';
import { Breadcrumbs } from '../components/Breadcrumbs';

const PageWrap = ({ title, children }: any) => (
  <div className="container" style={{ padding: '4rem 1.5rem', maxWidth: '800px', margin: '0 auto', minHeight: '70vh' }}>
    <Breadcrumbs items={[{ label: title }]} />
    <h1 style={{ marginBottom: '2.5rem', fontSize: '2.5rem' }}>{title}</h1>
    <div style={{ fontSize: '1.125rem', lineHeight: 1.8, color: 'var(--color-navy)' }}>
      {children}
    </div>
  </div>
);

export const About = () => (
  <PageWrap title="About Home Project Calculator">
    <p style={{ marginBottom: '1.5rem' }}>Home Project Calculator is a collection of simple tools designed to help homeowners, DIYers, and project planners estimate quantities, measurements, and material requirements.</p>
    <p style={{ marginBottom: '1.5rem' }}>We believe that planning a project shouldn't require complex spreadsheets or paid software. Our tools are built to be accessible, completely free, and incredibly fast.</p>
    
    <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '1.5rem' }}>Core features:</h3>
    <ul style={{ listStyle: 'disc', paddingLeft: '1.5rem', marginBottom: '2rem' }}>
      <li>No account or registration required.</li>
      <li>Calculations run instantly in your browser.</li>
      <li>Full support for both Metric and Imperial units.</li>
      <li>Localized formats for multiple languages.</li>
      <li>Ability to enter your own local material prices for accurate cost estimates.</li>
    </ul>
    
    <p>Please note that all tools provide estimates for planning purposes. Always consult professional advice for structural, safety, or load-bearing projects.</p>
  </PageWrap>
);

export const Privacy = () => (
  <PageWrap title="Privacy Policy">
    <p style={{ marginBottom: '1.5rem' }}>Last updated: September 2026</p>
    <p style={{ marginBottom: '1.5rem' }}>At Home Project Calculator, your privacy is a priority. We have designed our tools to work entirely within your web browser.</p>
    
    <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '1.25rem' }}>Data Collection</h3>
    <p style={{ marginBottom: '1.5rem' }}>We do not require you to create an account, and we do not collect personal identifiable information (PII) during your use of our calculators.</p>
    
    <h3 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '1.25rem' }}>Local Storage</h3>
    <p style={{ marginBottom: '1.5rem' }}>To provide a better user experience, we save your basic preferences (such as preferred Language, Country, Currency, and Unit System) in your browser's Local Storage. This data never leaves your device and is not sent to our servers.</p>
    
    <h3 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '1.25rem' }}>Future Analytics</h3>
    <p style={{ marginBottom: '1.5rem' }}>We reserve the right to implement anonymous traffic analytics (such as page views) in the future to help us improve the website. Any such implementation will respect standard Do Not Track (DNT) requests.</p>
  </PageWrap>
);

export const Terms = () => (
  <PageWrap title="Terms of Service">
    <p style={{ marginBottom: '1.5rem' }}>By accessing and using Home Project Calculator, you agree to these Terms of Service.</p>
    
    <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '1.25rem' }}>Use of the Website</h3>
    <p style={{ marginBottom: '1.5rem' }}>The calculators provided on this website are free tools intended for general planning and estimation. You may use them for personal or professional planning purposes.</p>
    
    <h3 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '1.25rem' }}>Estimates and Accuracy</h3>
    <p style={{ marginBottom: '1.5rem' }}>All calculations generated by this website are estimates. While we strive for mathematical accuracy, we cannot guarantee that the results will exactly match your real-world requirements due to variations in materials, waste, site conditions, and manufacturer specifications.</p>
    
    <h3 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '1.25rem' }}>User Responsibility</h3>
    <p style={{ marginBottom: '1.5rem' }}>You are solely responsible for verifying the accuracy of measurements and quantities before purchasing materials or beginning construction. Home Project Calculator is not liable for material shortages, overages, financial losses, or structural defects resulting from the use of these tools.</p>
  </PageWrap>
);

export const Disclaimer = () => (
  <PageWrap title="Disclaimer">
    <p style={{ marginBottom: '1.5rem', fontWeight: 600 }}>Calculations provided by Home Project Calculator are estimates intended for preliminary planning purposes only.</p>
    
    <ul style={{ listStyle: 'disc', paddingLeft: '1.5rem', marginBottom: '2rem' }}>
      <li style={{ marginBottom: '0.5rem' }}><strong>Product Coverage Varies:</strong> Paint coverage, tile breakage, and material yields vary significantly by manufacturer and environmental conditions.</li>
      <li style={{ marginBottom: '0.5rem' }}><strong>Material Density:</strong> Aggregate materials like gravel or soil can vary in weight depending on composition and moisture content.</li>
      <li style={{ marginBottom: '0.5rem' }}><strong>Verify Measurements:</strong> Always double-check your site measurements before purchasing materials.</li>
      <li style={{ marginBottom: '0.5rem' }}><strong>Professional Advice:</strong> For projects involving structural integrity, safety, electrical, or plumbing systems, always consult a licensed professional or structural engineer.</li>
    </ul>
  </PageWrap>
);

export const Contact = () => (
  <PageWrap title="Contact Us">
    <p style={{ marginBottom: '1.5rem' }}>Have a question, a suggestion for a new calculator, or found an issue with an existing tool?</p>
    <div style={{ background: 'var(--color-surface)', padding: '2rem', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border)', textAlign: 'center', margin: '3rem 0' }}>
      <p style={{ marginBottom: '1rem', color: 'var(--color-text-muted)' }}>You can reach us at:</p>
      <a href="mailto:hello@homeprojectcalculator.com" style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--color-primary)' }}>hello@homeprojectcalculator.com</a>
    </div>
    <p style={{ fontSize: '0.9rem', color: 'var(--color-text-muted)' }}>* Note: We are currently unable to provide custom project planning advice or verify individual structural calculations via email.</p>
  </PageWrap>
);

export const HowItWorks = () => (
  <PageWrap title="How it works">
    <p style={{ marginBottom: '3rem', fontSize: '1.25rem' }}>Using Home Project Calculator is designed to be as straightforward as possible.</p>
    
    <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem' }}>
      <div>
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ background: 'var(--color-primary)', color: 'white', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: '0.875rem' }}>1</span>
          Choose a calculator
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', paddingLeft: '2.5rem' }}>Find the specific tool you need (e.g. Concrete, Paint, Square Footage) via the homepage search or the main calculators directory.</p>
      </div>
      <div>
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ background: 'var(--color-primary)', color: 'white', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: '0.875rem' }}>2</span>
          Enter measurements
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', paddingLeft: '2.5rem' }}>Input your site dimensions. The calculators automatically respect your preferred metric or imperial unit settings.</p>
      </div>
      <div>
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ background: 'var(--color-primary)', color: 'white', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: '0.875rem' }}>3</span>
          Adjust waste and options
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', paddingLeft: '2.5rem' }}>Most construction projects require extra material to account for cutting, spills, and mistakes. We provide sensible defaults (usually 10%), but you can adjust these to fit your project.</p>
      </div>
      <div>
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ background: 'var(--color-primary)', color: 'white', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: '0.875rem' }}>4</span>
          Review the estimate
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', paddingLeft: '2.5rem' }}>Your results update instantly as you type. No page reloads are necessary.</p>
      </div>
      <div>
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ background: 'var(--color-primary)', color: 'white', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontSize: '0.875rem' }}>5</span>
          Enter local pricing (Optional)
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', paddingLeft: '2.5rem' }}>If you know the local cost of materials, enter it in the Cost Estimation section to instantly generate a budget estimate alongside your material quantities.</p>
      </div>
    </div>
  </PageWrap>
);
`);

// ==========================================
// 2. PROJECT PAGES
// ==========================================
write('src/pages/ProjectPages.tsx', `
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { Breadcrumbs } from '../components/Breadcrumbs';
import { ArrowRight, Box, Paintbrush, Grid2x2, Pickaxe, Ruler, Droplets, Home as HomeIcon, Trees, Car, BedDouble } from 'lucide-react';

const PROJECTS: Record<string, any> = {
  patio: {
    title: 'Building a Patio',
    desc: 'Planning a new outdoor patio? Start by measuring the area, then estimate the base materials and concrete you may need.',
    icon: <Box size={48} />,
    tools: [
      { step: 1, name: 'Measure your area', to: '/square-footage-calculator', icon: <Ruler size={24} /> },
      { step: 2, name: 'Estimate base gravel', to: '/gravel-calculator', icon: <Pickaxe size={24} /> },
      { step: 3, name: 'Calculate concrete (if pouring a slab)', to: '/concrete-calculator', icon: <Box size={24} /> }
    ],
    comingSoon: ['Paver Calculator']
  },
  bathroom: {
    title: 'Renovating a Bathroom',
    desc: 'Calculate the essential materials needed for a bathroom remodel.',
    icon: <Droplets size={48} />,
    tools: [
      { step: 1, name: 'Measure floor space', to: '/square-footage-calculator', icon: <Ruler size={24} /> },
      { step: 2, name: 'Calculate wall and floor tiles', to: '/tile-calculator', icon: <Grid2x2 size={24} /> },
      { step: 3, name: 'Estimate ceiling and trim paint', to: '/paint-calculator', icon: <Paintbrush size={24} /> }
    ],
    comingSoon: ['Grout Calculator', 'Drywall Calculator']
  },
  kitchen: {
    title: 'Updating a Kitchen',
    desc: 'Plan the flooring and paint required for your kitchen project.',
    icon: <HomeIcon size={48} />,
    tools: [
      { step: 1, name: 'Calculate floor tiles', to: '/tile-calculator', icon: <Grid2x2 size={24} /> },
      { step: 2, name: 'Estimate wall paint', to: '/paint-calculator', icon: <Paintbrush size={24} /> }
    ],
    comingSoon: ['Backsplash Calculator', 'Cabinet Area Calculator']
  },
  garden: {
    title: 'Improving your Garden',
    desc: 'Calculate landscaping materials for your outdoor space.',
    icon: <Trees size={48} />,
    tools: [
      { step: 1, name: 'Measure garden beds', to: '/square-footage-calculator', icon: <Ruler size={24} /> },
      { step: 2, name: 'Calculate decorative gravel/stones', to: '/gravel-calculator', icon: <Pickaxe size={24} /> }
    ],
    comingSoon: ['Soil Calculator', 'Mulch Calculator', 'Fence Calculator']
  },
  driveway: {
    title: 'Building a Driveway',
    desc: 'Estimate the bulk materials required for a new driveway.',
    icon: <Car size={48} />,
    tools: [
      { step: 1, name: 'Calculate base gravel', to: '/gravel-calculator', icon: <Pickaxe size={24} /> },
      { step: 2, name: 'Calculate concrete', to: '/concrete-calculator', icon: <Box size={24} /> }
    ],
    comingSoon: ['Asphalt Calculator', 'Paver Calculator']
  },
  bedroom: {
    title: 'Refreshing a Bedroom',
    desc: 'Quickly plan a bedroom makeover with our interior tools.',
    icon: <BedDouble size={48} />,
    tools: [
      { step: 1, name: 'Measure the room', to: '/square-footage-calculator', icon: <Ruler size={24} /> },
      { step: 2, name: 'Estimate wall paint', to: '/paint-calculator', icon: <Paintbrush size={24} /> }
    ],
    comingSoon: ['Hardwood Flooring Calculator', 'Carpet Calculator']
  }
};

export const ProjectPage = () => {
  const { id } = useParams();
  const project = PROJECTS[id || ''];

  if (!project) {
    return <div className="container" style={{ padding: '6rem 0', textAlign: 'center' }}>Project not found.</div>;
  }

  return (
    <div className="container" style={{ padding: '4rem 1.5rem', minHeight: '80vh' }}>
      <Breadcrumbs items={[{ label: 'Projects' }, { label: project.title }]} />
      
      <div style={{ textAlign: 'center', marginBottom: '4rem', maxWidth: '800px', margin: '0 auto 4rem auto' }}>
        <div style={{ display: 'inline-flex', padding: '1.5rem', background: 'var(--color-surface-alt)', color: 'var(--color-navy)', borderRadius: '50%', marginBottom: '1.5rem' }}>
          {project.icon}
        </div>
        <h1 style={{ marginBottom: '1rem', fontSize: '2.5rem' }}>{project.title}</h1>
        <p style={{ fontSize: '1.25rem', color: 'var(--color-text-muted)' }}>{project.desc}</p>
      </div>

      <div style={{ maxWidth: '600px', margin: '0 auto' }}>
        <h3 style={{ marginBottom: '2rem', fontSize: '1.25rem', borderBottom: '1px solid var(--color-border)', paddingBottom: '1rem' }}>Recommended Tools</h3>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {project.tools.map((tool: any, i: number) => (
            <Link to={tool.to} key={i} className="card" style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', padding: '1.5rem', transition: 'var(--transition)' }}>
              <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--color-text-muted)' }}>0{tool.step}</div>
              <div style={{ color: 'var(--color-primary)', background: 'var(--color-primary-light)', padding: '0.75rem', borderRadius: '12px' }}>
                {tool.icon}
              </div>
              <div style={{ flex: 1, fontWeight: 600, fontSize: '1.125rem' }}>{tool.name}</div>
              <ArrowRight size={20} color="var(--color-text-muted)" />
            </Link>
          ))}
          
          {project.comingSoon.map((toolName: string, i: number) => (
            <div key={\`soon-\${i}\`} style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', padding: '1.5rem', background: 'var(--color-surface-alt)', borderRadius: 'var(--radius-lg)', border: '1px dashed var(--color-border)', opacity: 0.8 }}>
              <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--color-text-muted)', visibility: 'hidden' }}>00</div>
              <div style={{ flex: 1, fontWeight: 600, color: 'var(--color-text-muted)' }}>{toolName}</div>
              <span style={{ fontSize: '0.75rem', fontWeight: 700, letterSpacing: '0.05em', color: 'var(--color-text-muted)', background: 'white', padding: '0.25rem 0.75rem', borderRadius: '99px' }}>COMING SOON</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
`);

// ==========================================
// 3. APP ROUTING UPDATE
// ==========================================
write('src/App.tsx', `
import React, { useEffect } from 'react';
import { BrowserRouter, Routes, Route, useLocation } from 'react-router-dom';
import { SettingsProvider } from './contexts/SettingsContext';
import { Header } from './components/Header';
import { Footer } from './components/Footer';
import { Home } from './pages/Home';
import { ConcreteCalculator } from './pages/ConcreteCalculator';
import { PaintCalculator } from './pages/PaintCalculator';
import { GravelCalculator } from './pages/GravelCalculator';
import { TileCalculator } from './pages/TileCalculator';
import { SquareFootageCalculator } from './pages/SquareFootageCalculator';
import { CalculatorsDirectory } from './pages/CalculatorsDirectory';
import { ProjectPage } from './pages/ProjectPages';
import { About, Privacy, Terms, Disclaimer, Contact, HowItWorks } from './pages/StaticPages';
import { BackToTop } from './components/BackToTop';

const ScrollToTop = () => {
  const { pathname } = useLocation();
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);
  return null;
};

function App() {
  return (
    <SettingsProvider>
      <BrowserRouter>
        <ScrollToTop />
        <Header />
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/calculators" element={<CalculatorsDirectory />} />
          <Route path="/concrete-calculator" element={<ConcreteCalculator />} />
          <Route path="/paint-calculator" element={<PaintCalculator />} />
          <Route path="/gravel-calculator" element={<GravelCalculator />} />
          <Route path="/tile-calculator" element={<TileCalculator />} />
          <Route path="/square-footage-calculator" element={<SquareFootageCalculator />} />
          
          <Route path="/projects/:id" element={<ProjectPage />} />
          
          <Route path="/about" element={<About />} />
          <Route path="/privacy" element={<Privacy />} />
          <Route path="/terms" element={<Terms />} />
          <Route path="/disclaimer" element={<Disclaimer />} />
          <Route path="/contact" element={<Contact />} />
          <Route path="/how-it-works" element={<HowItWorks />} />
        </Routes>
        <Footer />
        <BackToTop />
      </BrowserRouter>
    </SettingsProvider>
  );
}

export default App;
`);
