const fs = require('fs');
const path = require('path');

const files = ['en.ts', 'fr.ts', 'es.ts', 'pt.ts', 'it.ts', 'ar.ts'];

const keysToAdd = {
  "en": {
    "projects.patio.title": "Patio & Decking",
    "projects.patio.desc": "Plan the foundation and materials for your outdoor space.",
    "projects.bathroom.title": "Bathroom Remodel",
    "projects.bathroom.desc": "Calculate tiles, paint, and finishing materials.",
    "projects.kitchen.title": "Kitchen Update",
    "projects.kitchen.desc": "Estimate flooring and wall paint.",
    "projects.garden.title": "Garden Beds",
    "projects.garden.desc": "Measure soil, mulch, and decorative gravel.",
    "projects.driveway.title": "Driveway & Path",
    "projects.driveway.desc": "Calculate base gravel and surface concrete.",
    "projects.bedroom.title": "Bedroom Refresh",
    "projects.bedroom.desc": "Estimate paint and flooring needs.",
    "projects.step.measureArea": "Measure Area",
    "projects.step.estimateGravel": "Estimate Gravel",
    "projects.step.calcConcrete": "Calculate Concrete",
    "projects.step.measureFloor": "Measure Floor",
    "projects.step.calcWallFloorTiles": "Calculate Wall & Floor Tiles",
    "projects.step.estimateCeilingPaint": "Estimate Ceiling Paint",
    "projects.step.calcFloorTiles": "Calculate Floor Tiles",
    "projects.step.estimateWallPaint": "Estimate Wall Paint",
    "projects.step.measureBeds": "Measure Beds",
    "projects.step.calcDecoGravel": "Calculate Decorative Gravel",
    "projects.step.calcConcreteSimple": "Calculate Concrete",
    "projects.step.measureRoom": "Measure Room",
    "calc.paver": "Paver Calculator",
    "calc.grout": "Grout Calculator",
    "calc.drywall": "Drywall Calculator",
    "calc.backsplash": "Backsplash Calculator",
    "calc.cabinet": "Cabinet Calculator",
    "calc.soil": "Soil Calculator",
    "calc.mulch": "Mulch Calculator",
    "calc.fence": "Fence Calculator",
    "calc.asphalt": "Asphalt Calculator",
    "calc.hardwood": "Hardwood Calculator",
    "calc.carpet": "Carpet Calculator",
    "common.projectNotFound": "Project not found.",
    "common.recommendedTools": "Recommended Tools",
    "common.comingSoon": "Coming Soon",
    "static.terms.title": "Terms of Service",
    "static.terms.p1": "By accessing and using Home Project Calculator, you agree to these Terms of Service.",
    "static.terms.useTitle": "Use of the Website",
    "static.terms.useDesc": "The calculators provided on this website are free tools intended for general planning and estimation. You may use them for personal or professional planning purposes.",
    "static.terms.accTitle": "Estimates and Accuracy",
    "static.terms.accDesc": "All calculations generated by this website are estimates. While we strive for mathematical accuracy, we cannot guarantee that the results will exactly match your real-world requirements due to variations in materials, waste, site conditions, and manufacturer specifications.",
    "static.terms.userTitle": "User Responsibility",
    "static.terms.userDesc": "You are solely responsible for verifying the accuracy of measurements and quantities before purchasing materials or beginning construction. Home Project Calculator is not liable for material shortages, overages, financial losses, or structural defects resulting from the use of these tools.",
    "static.disclaimer.title": "Disclaimer",
    "static.disclaimer.p1": "Calculations provided by Home Project Calculator are estimates intended for preliminary planning purposes only.",
    "static.disclaimer.li1s": "Product Coverage Varies:",
    "static.disclaimer.li1": "Paint coverage, tile breakage, and material yields vary significantly by manufacturer and environmental conditions.",
    "static.disclaimer.li2s": "Material Density:",
    "static.disclaimer.li2": "Aggregate materials like gravel or soil can vary in weight depending on composition and moisture content.",
    "static.disclaimer.li3s": "Verify Measurements:",
    "static.disclaimer.li3": "Always double-check your site measurements before purchasing materials.",
    "static.disclaimer.li4s": "Professional Advice:",
    "static.disclaimer.li4": "For projects involving structural integrity, safety, electrical, or plumbing systems, always consult a licensed professional or structural engineer.",
    "static.contact.title": "Contact Us",
    "static.contact.p1": "Have a question, a suggestion for a new calculator, or found an issue with an existing tool?",
    "static.contact.reachUs": "You can reach us at:",
    "static.contact.note": "* Note: We are currently unable to provide custom project planning advice or verify individual structural calculations via email."
  },
  "fr": {
    "projects.patio.title": "Terrasse & Deck",
    "projects.patio.desc": "Planifiez les fondations et les matériaux pour votre espace extérieur.",
    "projects.bathroom.title": "Rénovation Salle de Bain",
    "projects.bathroom.desc": "Calculez le carrelage, la peinture et les finitions.",
    "projects.kitchen.title": "Mise à jour Cuisine",
    "projects.kitchen.desc": "Estimez le sol et la peinture murale.",
    "projects.garden.title": "Jardin & Massifs",
    "projects.garden.desc": "Mesurez la terre, le paillis et le gravier décoratif.",
    "projects.driveway.title": "Allée & Chemin",
    "projects.driveway.desc": "Calculez le gravier de base et la surface en béton.",
    "projects.bedroom.title": "Rafraîchissement Chambre",
    "projects.bedroom.desc": "Estimez la peinture et les besoins en revêtement de sol.",
    "projects.step.measureArea": "Mesurer la surface",
    "projects.step.estimateGravel": "Estimer le gravier",
    "projects.step.calcConcrete": "Calculer le béton",
    "projects.step.measureFloor": "Mesurer le sol",
    "projects.step.calcWallFloorTiles": "Calculer le carrelage (sol/mur)",
    "projects.step.estimateCeilingPaint": "Estimer la peinture plafond",
    "projects.step.calcFloorTiles": "Calculer le carrelage (sol)",
    "projects.step.estimateWallPaint": "Estimer la peinture murale",
    "projects.step.measureBeds": "Mesurer les massifs",
    "projects.step.calcDecoGravel": "Calculer le gravier décoratif",
    "projects.step.calcConcreteSimple": "Calculer le béton",
    "projects.step.measureRoom": "Mesurer la pièce",
    "calc.paver": "Calculateur de Pavés",
    "calc.grout": "Calculateur de Joint",
    "calc.drywall": "Calculateur de Placo",
    "calc.backsplash": "Calculateur de Crédence",
    "calc.cabinet": "Calculateur de Placards",
    "calc.soil": "Calculateur de Terre",
    "calc.mulch": "Calculateur de Paillis",
    "calc.fence": "Calculateur de Clôture",
    "calc.asphalt": "Calculateur d'Asphalte",
    "calc.hardwood": "Calculateur de Parquet",
    "calc.carpet": "Calculateur de Moquette",
    "common.projectNotFound": "Projet non trouvé.",
    "common.recommendedTools": "Outils Recommandés",
    "common.comingSoon": "Bientôt",
    "static.terms.title": "Conditions d'utilisation",
    "static.terms.p1": "En accédant et en utilisant Home Project Calculator, vous acceptez ces Conditions d'utilisation.",
    "static.terms.useTitle": "Utilisation du site Web",
    "static.terms.useDesc": "Les calculateurs fournis sur ce site sont des outils gratuits destinés à la planification générale et à l'estimation. Vous pouvez les utiliser à des fins de planification personnelle ou professionnelle.",
    "static.terms.accTitle": "Estimations et Précision",
    "static.terms.accDesc": "Tous les calculs générés par ce site sont des estimations. Bien que nous nous efforcions d'assurer l'exactitude mathématique, nous ne pouvons garantir que les résultats correspondront exactement à vos besoins réels en raison des variations de matériaux, des déchets, des conditions du site et des spécifications du fabricant.",
    "static.terms.userTitle": "Responsabilité de l'utilisateur",
    "static.terms.userDesc": "Vous êtes seul responsable de vérifier l'exactitude des mesures et des quantités avant d'acheter des matériaux ou de commencer la construction. Home Project Calculator n'est pas responsable des pénuries de matériaux, des excédents, des pertes financières ou des défauts structurels résultant de l'utilisation de ces outils.",
    "static.disclaimer.title": "Avis de non-responsabilité",
    "static.disclaimer.p1": "Les calculs fournis par Home Project Calculator sont des estimations destinées à des fins de planification préliminaire uniquement.",
    "static.disclaimer.li1s": "La couverture des produits varie :",
    "static.disclaimer.li1": "La couverture de la peinture, la casse des carreaux et les rendements des matériaux varient considérablement selon le fabricant et les conditions environnementales.",
    "static.disclaimer.li2s": "Densité des matériaux :",
    "static.disclaimer.li2": "Les matériaux agrégats comme le gravier ou la terre peuvent varier en poids en fonction de la composition et de la teneur en humidité.",
    "static.disclaimer.li3s": "Vérifiez les mesures :",
    "static.disclaimer.li3": "Revérifiez toujours vos mesures sur le site avant d'acheter des matériaux.",
    "static.disclaimer.li4s": "Avis professionnel :",
    "static.disclaimer.li4": "Pour les projets impliquant l'intégrité structurelle, la sécurité, l'électricité ou la plomberie, consultez toujours un professionnel agréé ou un ingénieur en structure.",
    "static.contact.title": "Nous contacter",
    "static.contact.p1": "Vous avez une question, une suggestion pour un nouveau calculateur ou avez trouvé un problème avec un outil existant ?",
    "static.contact.reachUs": "Vous pouvez nous joindre à :",
    "static.contact.note": "* Remarque : Nous ne sommes actuellement pas en mesure de fournir des conseils de planification de projets personnalisés ni de vérifier des calculs structurels individuels par courriel."
  }
};

files.forEach(file => {
  const filePath = path.join(__dirname, 'src', 'i18n', file);
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, 'utf8');
    
    // Find the last closing brace
    const lastBraceIndex = content.lastIndexOf('}');
    if (lastBraceIndex !== -1) {
      const lang = file.replace('.ts', '');
      const toAdd = keysToAdd[lang] || keysToAdd['en']; // fallback to en if missing
      
      let addition = '';
      for (const [key, value] of Object.entries(toAdd)) {
        // Only add if key not present
        if (!content.includes('"' + key + '"')) {
          addition += `,\n  "${key}": ${JSON.stringify(value)}`;
        }
      }
      
      if (addition) {
        content = content.slice(0, lastBraceIndex) + addition + '\n' + content.slice(lastBraceIndex);
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`Updated ${file}`);
      }
    }
  }
});
