const fs = require('fs');
const newKeys = {
  // Tile
  'calc.tile.title': 'Tile Calculator',
  'calc.tile.description': 'Plan flooring and wall tiles layouts.',
  'calc.tile.estimateReady': 'Estimate ready',
  'calc.tile.yourEstimate': 'Your Estimate',
  'calc.tile.tiles': 'tiles',
  'calc.tile.orBoxes': 'Or {boxes} boxes ({waste}% waste included)',
  'calc.tile.estimatedCost': 'Estimated Cost',
  'calc.tile.howItWorks': 'How to calculate tile requirements',
  'calc.tile.howItWorksDesc': 'Whether you are tiling a bathroom floor or a kitchen backsplash, accurate measurement is crucial. Tiles are typically sold by the box, so estimating the total required tiles allows you to purchase the correct number of boxes from the same manufacturing batch (to ensure consistent coloring).',
  'calc.tile.formula': 'The Formula',
  'calc.tile.example': 'Example Calculation',
  'calc.tile.exampleDesc': 'Tiling a 4m × 3m room using 0.3m × 0.3m (30cm) ceramic tiles:',
  'calc.tile.ex1': 'Room Area: 4m × 3m = 12 m²',
  'calc.tile.ex2': 'Tile Area: 0.3m × 0.3m = 0.09 m²',
  'calc.tile.ex3': 'Base Tiles Needed: 12 ÷ 0.09 = 133.3 tiles',
  'calc.tile.ex4': 'With 10% Waste: 133.3 × 1.10 = 147 tiles',
  'calc.tile.whyWaste': 'Why add a waste factor?',
  'calc.tile.whyWasteDesc': 'When installing tiles, you will inevitably need to cut tiles to fit the edges of the room, around pipes, or into corners. These cut pieces are often unusable elsewhere. Furthermore, tiles can crack or break during installation. A standard recommendation is 10% extra for simple rectangular rooms, but complex layouts (like diagonal/herringbone patterns) or rooms with many obstacles may require 15% to 20% waste.',
  
  // Static pages
  'static.about.title': 'About',
  'static.about.p1': 'Home Project Calculator is a collection of simple tools designed to help homeowners, DIYers, and project planners estimate quantities, measurements, and material requirements.',
  'static.about.p2': 'We believe that planning a project shouldn\'t require complex spreadsheets or paid software. Our tools are built to be accessible, completely free, and incredibly fast.',
  'static.about.features': 'Core features:',
  'static.about.f1': 'No account or registration required.',
  'static.about.f2': 'Calculations run instantly in your browser.',
  'static.about.f3': 'Full support for both Metric and Imperial units.',
  'static.about.f4': 'Localized formats for multiple languages.',
  'static.about.f5': 'Ability to enter your own local material prices for accurate cost estimates.',
  'static.about.disclaimer': 'Please note that all tools provide estimates for planning purposes. Always consult professional advice for structural, safety, or load-bearing projects.',
  
  'static.privacy.title': 'Privacy Policy',
  'static.privacy.updated': 'Last updated: September 2026',
  'static.privacy.p1': 'At Home Project Calculator, your privacy is a priority. We have designed our tools to work entirely within your web browser.',
  'static.privacy.dataTitle': 'Data Collection',
  'static.privacy.dataDesc': 'We do not require you to create an account, and we do not collect personal identifiable information (PII) during your use of our calculators.',
  'static.privacy.localTitle': 'Local Storage',
  'static.privacy.localDesc': 'To provide a better user experience, we save your basic preferences (such as preferred Language, Country, Currency, and Unit System) in your browser\'s Local Storage. This data never leaves your device and is not sent to our servers.',
  'static.privacy.analyticsTitle': 'Future Analytics',
  'static.privacy.analyticsDesc': 'We reserve the right to implement anonymous traffic analytics (such as page views) in the future to help us improve the website. Any such implementation will respect standard Do Not Track (DNT) requests.',
  
  'static.terms.title': 'Terms of Service',
  'static.terms.p1': 'By accessing and using Home Project Calculator, you agree to these Terms of Service.',
  'static.terms.useTitle': 'Use of the Website',
  'static.terms.useDesc': 'The calculators provided on this website are free tools intended for general planning and estimation. You may use them for personal or professional planning purposes.',
  'static.terms.estimatesTitle': 'Estimates and Accuracy',
  'static.terms.estimatesDesc': 'All calculations generated by this website are estimates. While we strive for mathematical accuracy, we cannot guarantee that the results will exactly match your real-world requirements due to variations in materials, waste, site conditions, and manufacturer specifications.',
  'static.terms.userTitle': 'User Responsibility',
  'static.terms.userDesc': 'You are solely responsible for verifying the accuracy of measurements and quantities before purchasing materials or beginning construction. Home Project Calculator is not liable for material shortages, overages, financial losses, or structural defects resulting from the use of these tools.',
  
  'static.disclaimer.title': 'Disclaimer',
  'static.disclaimer.p1': 'Calculations provided by Home Project Calculator are estimates intended for preliminary planning purposes only.',
  'static.disclaimer.d1': 'Product Coverage Varies: Paint coverage, tile breakage, and material yields vary significantly by manufacturer and environmental conditions.',
  'static.disclaimer.d2': 'Material Density: Aggregate materials like gravel or soil can vary in weight depending on composition and moisture content.',
  'static.disclaimer.d3': 'Verify Measurements: Always double-check your site measurements before purchasing materials.',
  'static.disclaimer.d4': 'Professional Advice: For projects involving structural integrity, safety, electrical, or plumbing systems, always consult a licensed professional or structural engineer.',
  
  'static.contact.title': 'Contact',
  'static.contact.p1': 'Have a question, a suggestion for a new calculator, or found an issue with an existing tool?',
  'static.contact.p2': 'You can reach us at:',
  
  'static.hiw.title': 'How It Works',
  'static.hiw.p1': 'Using Home Project Calculator is designed to be as straightforward as possible.',
  'static.hiw.steps.1.t': '1. Choose your tool',
  'static.hiw.steps.1.d': 'Navigate to our Calculators or Projects section to find the tool that matches your task.',
  'static.hiw.steps.2.t': '2. Set your preferences',
  'static.hiw.steps.2.d': 'Use the gear icon in the header to select your preferred unit system (Metric or Imperial) and currency.',
  'static.hiw.steps.3.t': '3. Enter measurements',
  'static.hiw.steps.3.d': 'Input the dimensions of your project space. The calculator updates instantly.',
  'static.hiw.steps.4.t': '4. Adjust waste & cost',
  'static.hiw.steps.4.d': 'Modify the waste factor and price per unit to get a realistic estimate before you head to the store.',
  
  'calc.gravel.title': 'Gravel Calculator',
  'calc.gravel.description': 'Estimate gravel or aggregate for landscaping.',
  'calc.paint.title': 'Paint Calculator',
  'calc.paint.description': 'Estimate how much paint you need for your walls.',
  'calc.area.title': 'Square Footage Calculator',
  'calc.area.description': 'Calculate total area for any rectangular space.'
};
const langs = ['en','fr','es','pt','it','ar'];
langs.forEach(lang => {
  const path = 'src/i18n/'+lang+'.ts';
  let content = fs.readFileSync(path, 'utf8');
  let dictEndIndex = content.lastIndexOf('}');
  let existingContent = content.substring(0, dictEndIndex);
  for (let key in newKeys) {
    if (!existingContent.includes("'" + key + "'") && !existingContent.includes('"' + key + '"')) {
      existingContent += ',\n  "' + key + '": "' + newKeys[key] + '"';
    }
  }
  existingContent += '\n};\n';
  fs.writeFileSync(path, existingContent);
});
console.log('Dictionaries updated!');
